import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.green.shade700,
          title: Text('Allohning 99 Ismi'),
        ),
        body: ListView(
          padding: EdgeInsets.all(16.0),
          children: allahNames.map((item) => Padding(
            padding: const EdgeInsets.symmetric(vertical: 8.0),
            child: Text(
              '${item['name']}: ${item['meaning']}',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
          )).toList(),
        ),
      ),
    );
  }
}

final List<Map<String, String>> allahNames = [
  {'name': 'Ar-Rahman', 'meaning': 'Mehribon'},
  {'name': 'Ar-Rahim', 'meaning': 'Raxmadli'},
  {'name': 'Al-Malik', 'meaning': 'Sahib'},
  {'name': 'Al-Quddus', 'meaning': 'Pok'},
  {'name': 'Al-Salam', 'meaning': 'Tinchlik beruvchi'},
  {'name': 'Al-Mu’min', 'meaning': 'Ishonchli'},
  {'name': 'Al-Muhaymin', 'meaning': 'Himoyachi'},
  {'name': 'Al-Aziz', 'meaning': 'G’olib'},
  {'name': 'Al-Jabbar', 'meaning': 'Zoravon'},
  {'name': 'Al-Mutakabbir', 'meaning': 'Buyuk'},
  {'name': 'Al-Xoliq', 'meaning': 'Yaratuvchi'},
  {'name': 'Al-Bari', 'meaning': 'Muvaffaqiyatli'},
  {'name': 'Al-Musavvir', 'meaning': 'Tasvirlovchi'},
  {'name': "Al-G'ffar" ,'meaning' : 'Ko‘p kechiruvchi'},
  {'name': 'Al-Qahhar', 'meaning': 'Yenguvchi'},
  {'name': 'Al-Vahhob', 'meaning': 'Ko‘p beruvchi'},
  {'name': 'Al-Razzaq', 'meaning': 'Ta’minlovchi'},
  {'name': 'Al-Fattah', 'meaning': 'Ochuvchi'},
  {'name': 'Al-Alim', 'meaning': 'Bilangan'},
  {'name': 'Al-Qabid', 'meaning': 'O‘ziga tortuvchi'},
  {'name': 'Al-Basit', 'meaning': 'Kengaytiruvchi'},
  {'name': 'Al-Xafiz', 'meaning': 'Pastga tushiruvchi'},
  {'name': 'Al-Rafi', 'meaning': 'Yuksaltiruvchi'},
  {'name': 'Al-Mu’izz', 'meaning': 'Shon-sharaf beruvchi'},
  {'name': 'Al-Muzil', 'meaning': 'Nobodir qiluvchi'},
  {'name': 'Al-Sami', 'meaning': 'Eshituvchi'},
  {'name': 'Al-Basir', 'meaning': 'Ko‘ruvchi'},
  {'name': 'Al-Hakam', 'meaning': 'Hakim'},
  {'name': 'Al-Adl', 'meaning': 'Adolatli'},
  {'name': 'Al-Latif', 'meaning': 'Muhayyo'},
  {'name': 'Al-Xabir', 'meaning': 'Bilan biluvchi'},
  {'name': 'Al-Halim', 'meaning': 'Bardoshli'},
  {'name': 'Al-Azim', 'meaning': 'Buyuk'},
  {'name': 'Al-Ghafur', 'meaning': 'Kechiruvchi'},
  {'name': 'Al-Shakur', 'meaning': 'Minatdor'},
  {'name': 'Al-Aliyy', 'meaning': 'Yuksak'},
  {'name': 'Al-Kabir', 'meaning': 'Katta'},
  {'name': 'Al-Hafiz', 'meaning': 'Saqlovchi'},
  {'name': 'Al-Muqit', 'meaning': 'Ta’minlovchi'},
  {'name': 'Al-Hasiib', 'meaning': 'Hisoblaguvchi'},
  {'name': 'Al-Jalil', 'meaning': 'Aziz'},
  {'name': 'Al-Karim', 'meaning': 'Beg‘araz'},
  {'name': 'Al-Raqib', 'meaning': 'Nazoratchi'},
  {'name': 'Al-Mujib', 'meaning': 'Duo qiluvchi'},
  {'name': 'Al-Vasi', 'meaning': 'Keng'},
  {'name': 'Al-Hakim', 'meaning': 'Hikmatli'},
  {'name': 'Al-Vadud', 'meaning': 'Sevuvchi'},
  {'name': 'Al-Majid', 'meaning': 'Shon-sharafli'},
  {'name': 'Al-Ba’ith', 'meaning': 'Tirik qiluvchi'},
  {'name': 'Al-Shahid', 'meaning': 'Guvoh'},
  {'name': 'Al-Haqq', 'meaning': 'Haqqoniy'},
  {'name': 'Al-Vakil', 'meaning': 'Vekil'},
  {'name': 'Al-Qawi', 'meaning': 'Quvvatli'},
  {'name': 'Al-Matin', 'meaning': 'Mustahkam'},
  {'name': 'Al-Valiyy', 'meaning': 'Do‘st'},
  {'name': 'Al-Hamid', 'meaning': 'Hamda qiluvchi'},
  {'name': 'Al-Muhsi', 'meaning': 'Hisoblovchi'},
  {'name': 'Al-Mubdi', 'meaning': 'Yaratuvchi'},
  {'name': 'Al-Mu’id', 'meaning': 'Qaytaruvchi'},
  {'name': 'Al-Muhyi', 'meaning': 'Hayot beruvchi'},
  {'name': 'Al-Mumit', 'meaning': 'O‘ldiruvchi'},
  {'name': 'Al-Hayy', 'meaning': 'Yashovchi'},
  {'name': 'Al-Qayyum', 'meaning': 'Tayyorlovchi'},
  {'name': 'Al-Vajid', 'meaning': 'Topuvchi'},
  {'name': 'Al-Majid', 'meaning': 'Aziz'},
  {'name': 'Al-Mu’min', 'meaning': 'Ishonchli'},
  {'name': 'Al-Mutakabbir', 'meaning': 'Buyuk'},
  {'name': 'Al-Xoliq', 'meaning': 'Yaratuvchi'},
  {'name': 'Al-Bari’', 'meaning': 'Muvaffaqiyatli'},
  {'name': 'Al-Musavvir', 'meaning': 'Tasvirlovchi'},
  {'name': "Al-G'affar", 'meaning': 'Ko‘p kechiruvchi'},
  {'name': 'Al-Qahhar', 'meaning': 'Yenguvchi'},
  {'name': 'Al-Vahhab', 'meaning': 'Ko‘p beruvchi'},
  {'name': 'Al-Razzaq', 'meaning': 'Ta’minlovchi'},
  {'name': 'Al-Fattoh', 'meaning': 'Ochuvchi'},
  {'name': 'Al-Alim', 'meaning': 'Bilangan'},
  {'name': 'Al-Qabid', 'meaning': 'O‘ziga tortuvchi'},
  {'name': 'Al-Basit', 'meaning': 'Kengaytiruvchi'},
  {'name': 'Al-Khafid', 'meaning': 'Pastga tushiruvchi'},
  {'name': 'Al-Rafi’', 'meaning': 'Yuksaltiruvchi'},
  {'name': 'Al-Mu’izz', 'meaning': 'Shon-sharaf beruvchi'},
  {'name': 'Al-Muzil', 'meaning': 'Nobodir qiluvchi'},
  {'name': 'Al-Sami’', 'meaning': 'Eshituvchi'},
  {'name': 'Al-Basir', 'meaning': 'Ko‘ruvchi'},
  {'name': 'Al-Hakam', 'meaning': 'Hakim'},
  {'name': 'Al-Adl', 'meaning': 'Adolatli'},
  {'name': 'Al-Latif', 'meaning': 'Muhayyo'},
  {'name': 'Al-Khabir', 'meaning': 'Bilan biluvchi'},
  {'name': 'Al-Halim', 'meaning': 'Bardoshli'},
  {'name': 'Al-Azim', 'meaning': 'Buyuk'},
  {'name': 'Al-Ghafur', 'meaning': 'Kechiruvchi'},
  {'name': 'Al-Shakur', 'meaning': 'Minatdor'},
  {'name': 'Al-Aliyy', 'meaning': 'Yuksak'},
  {'name': 'Al-Kabir', 'meaning': 'Katta'},
  {'name': 'Al-Hafiz', 'meaning': 'Saqlovchi'},
  {'name': 'Al-Muqit', 'meaning': 'Ta’minlovchi'},
  {'name': 'Al-Hasiib', 'meaning': 'Hisoblaguvchi'},
  {'name': 'Al-Jalil', 'meaning': 'Aziz'},
  {'name': 'Al-Karim', 'meaning': 'Beg‘araz'},
  {'name': 'Al-Raqib', 'meaning': 'Nazoratchi'},
  {'name': 'Al-Mujib', 'meaning': 'Duo qiluvchi'},
  {'name': 'Al-Vasi’', 'meaning': 'Keng'},
  {'name': 'Al-Hakim', 'meaning': 'Hikmatli'},
  {'name': 'Al-Vadud', 'meaning': 'Sevuvchi'},
  {'name': 'Al-Majid', 'meaning': 'Shon-sharafli'},
  {'name': 'Al-Ba’ith', 'meaning': 'Tirik qiluvchi'},
  {'name': 'Al-Shahid', 'meaning': 'Guvoh'},
  {'name': 'Al-Haqq', 'meaning': 'Haqqoniy'},
  {'name': 'Al-Vakil', 'meaning': 'Vekil'},
  {'name': 'Al-Qavi', 'meaning': 'Quvvatli'},
  {'name': 'Al-Matin', 'meaning': 'Mustahkam'},
  {'name': 'Al-Valiyy', 'meaning': 'Do‘st'},
  {'name': 'Al-Hamid', 'meaning': 'Hamda qiluvchi'},
  {'name': 'Al-Muhsi', 'meaning': 'Hisoblovchi'},
  {'name': 'Al-Mubdi’', 'meaning': 'Yaratuvchi'},
  {'name': 'Al-Mu’id', 'meaning': 'Qaytaruvchi'},
  {'name': 'Al-Muhyi', 'meaning': 'Hayot beruvchi'},
  {'name': 'Al-Mumit', 'meaning': 'O‘ldiruvchi'},
  {'name': 'Al-Hayy', 'meaning': 'Yashovchi'},
  {'name': 'Al-Qayyum', 'meaning': 'Tayyorlovchi'},
  {'name': 'Al-Vajid', 'meaning': 'Topuvchi'},
];
